// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyInvestmentApp.Data;

#nullable disable

namespace MyInvestmentApp.Data.Migrations
{
    [DbContext(typeof(MyInvestmentAppDBContext))]
    [Migration("20221210015143_InitialDatabaseMigration")]
    partial class InitialDatabaseMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("MyInvestmentApp.Data.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("emailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("existingCustomer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("inquiryOptions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isTesolved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("userInquiry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("contacts");
                });

            modelBuilder.Entity("MyInvestmentApp.Data.Models.InvestmentCalc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("compoundsPerYear")
                        .HasColumnType("INTEGER");

                    b.Property<double>("futureValue")
                        .HasColumnType("REAL");

                    b.Property<int>("intrest")
                        .HasColumnType("INTEGER");

                    b.Property<int>("principle")
                        .HasColumnType("INTEGER");

                    b.Property<string>("whichUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("years")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("investmentCalcs");
                });
#pragma warning restore 612, 618
        }
    }
}
